version: '3'

services:
  test_api:
    build: .
    container_name: test_api
    restart: unless-stopped
    command: bash -c "npm run migration:run:test && npm run seed:up:test && npm run test"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-H", "Version: 1", "-sf", "http://api:${API_PORT}"]
      interval: 30s
      retries: 100
      start_period: 10s
    env_file:
      - .env

  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "0.0.0.0", "--silent"]
      interval: 30s
      retries: 100
      start_period: 10s
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$TEST_DB_NAME
      - MYSQL_ROOT_HOST=%
      - MYSQL_TCP_PORT=$TEST_DB_PORT
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql

networks:
  app-network:
    driver: bridge