version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.23.4
    environment:
      - DOMAIN=$DOMAIN
    ports:
      - 80:80
    volumes:
      - ./etc/nginx/templates-initiate:/etc/nginx/templates
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
    env_file:
      - .env

  certbot:
    container_name: certbot
    image: certbot/certbot:v2.5.0
    depends_on:
      - nginx
    command: >- 
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email $EMAIL --agree-tos --no-eff-email
             -d $DOMAIN
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
    env_file:
      - .env