version: '1'

services:
  api:
    container_name: api
    command: bash -c "npm run migration:run && npm run seed:up && npm run start:prod"
    depends_on:
      db:
        condition: service_healthy
    build: .
    restart: always
    ports:
      - $EXTERNAL_API_PORT:$API_PORT
    env_file:
      - .env

  db:
    container_name: db 
    image: mysql:8
    ports: 
      - $DB_PORT:$DB_PORT
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "0.0.0.0", "--silent"]
      interval: 30s
      retries: 100
      start_period: 10s
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_HOST=%
      - MYSQL_TCP_PORT=$DB_PORT
    env_file:
      - .env
    command: '--default-authentication-plugin=mysql_native_password'

#   test_db:
#     container_name: test_db 
#     image: mysql:8
#     ports: 
#       - $TEST_DB_PORT:$TEST_DB_PORT
#     restart: always
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "0.0.0.0", "--silent"]
#       interval: 30s
#       retries: 100
#       start_period: 10s
#     environment:
#       - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
#       - MYSQL_DATABASE=$TEST_DB_NAME
#       - MYSQL_ROOT_HOST=%
#       - MYSQL_TCP_PORT=$TEST_DB_PORT
#     env_file:
#       - .env
#     command: '--default-authentication-plugin=mysql_native_password'


volumes:
  dbdata:
    driver: local
