version: '1'

services:
  api:
    build: .
    container_name: api
    restart: unless-stopped
    ports:
      - 3005:3005
    command: bash -c "npm run migration:run && npm run seed:up && npm run start:prod"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./images:/app/images
    networks:
      - app-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://api:${API_PORT}"]
    #   interval: 30s
    #   retries: 10
    #   start_period: 10s
    env_file:
      - .env

  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "0.0.0.0", "--silent"]
      interval: 30s
      retries: 100
      start_period: 10s
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_HOST=%
      - MYSQL_TCP_PORT=$DB_PORT
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - api
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:3005"]
      interval: 30s
      retries: 10
      start_period: 10s
    env_file:
      - .env
    volumes:
      - .nginx/nginx.conf:/etc/nginx/nginx.conf:ro

#   test_db:
#     container_name: test_db 
#     image: mysql:8
#     ports: 
#       - $TEST_DB_PORT:$TEST_DB_PORT
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "0.0.0.0", "--silent"]
#       interval: 30s
#       retries: 100
#       start_period: 10s
#     environment:
#       - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
#       - MYSQL_DATABASE=$TEST_DB_NAME
#       - MYSQL_ROOT_HOST=%
#       - MYSQL_TCP_PORT=$TEST_DB_PORT
#     env_file:
#       - .env
#     command: '--default-authentication-plugin=mysql_native_password'

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: