import { Person } from "./interfaces/person.interface";

export class SamplePeopleData {
    readonly array: Person[] = [
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
        {
            name: "aaa",
            height: 123,
            mass: 123,
            hair_color: "",
            skin_color: "string",
            eye_color: "string",
            birth_year: "string",
            gender: "string",
            homeworld: "string",
            films: [],
            species: [],
            vehicles: [],
            starships: [],
            created: "",
            edited: "",
            url: "",
        },
    ];

    getArray(): Person[] {
        return this.array;
    }
}