import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTablesTest1681218175847 implements MigrationInterface {
    name = 'CreateTablesTest1681218175847'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`files\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`, \`name\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`planets\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL DEFAULT 'unknown', \`created\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`edited\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`rotation_period\` varchar(255) NOT NULL, \`orbital_period\` varchar(255) NOT NULL, \`diameter\` varchar(255) NOT NULL, \`climate\` varchar(255) NOT NULL, \`gravity\` varchar(255) NOT NULL, \`terrain\` varchar(255) NOT NULL, \`surface_water\` varchar(255) NOT NULL, \`population\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_70a170f032a2ca04a6ec6eb2d9\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`species\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL DEFAULT 'unknown', \`created\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`edited\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`classification\` varchar(255) NOT NULL, \`designation\` varchar(255) NOT NULL, \`average_height\` varchar(255) NOT NULL, \`skin_colors\` varchar(255) NOT NULL, \`hair_colors\` varchar(255) NOT NULL, \`eye_colors\` varchar(255) NOT NULL, \`average_lifespan\` varchar(255) NOT NULL, \`language\` varchar(255) NOT NULL, \`homeworldId\` int NULL, UNIQUE INDEX \`IDX_1adf701cac3b2c0f8bacb54774\` (\`name\`), UNIQUE INDEX \`REL_3427f7c92316561d7131c296bc\` (\`homeworldId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`starships\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL DEFAULT 'unknown', \`created\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`edited\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`model\` varchar(255) NOT NULL, \`manufacturer\` varchar(255) NOT NULL, \`cost_in_credits\` varchar(255) NOT NULL, \`length\` varchar(255) NOT NULL, \`max_atmosphering_speed\` varchar(255) NOT NULL, \`crew\` varchar(255) NOT NULL, \`passengers\` varchar(255) NOT NULL, \`cargo_capacity\` varchar(255) NOT NULL, \`consumables\` varchar(255) NOT NULL, \`hyperdrive_rating\` varchar(255) NOT NULL, \`MGLT\` varchar(255) NOT NULL, \`starship_class\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_41580e76da7903fb3827a3510e\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vehicles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL DEFAULT 'unknown', \`created\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`edited\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`model\` varchar(255) NOT NULL, \`manufacturer\` varchar(255) NOT NULL, \`cost_in_credits\` varchar(255) NOT NULL, \`length\` varchar(255) NOT NULL, \`max_atmosphering_speed\` varchar(255) NOT NULL, \`crew\` varchar(255) NOT NULL, \`passengers\` varchar(255) NOT NULL, \`cargo_capacity\` varchar(255) NOT NULL, \`consumables\` varchar(255) NOT NULL, \`vehicle_class\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_aa397b791341ed3615397050d4\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`people\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL DEFAULT 'unknown', \`created\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`edited\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`height\` varchar(255) NOT NULL, \`mass\` varchar(255) NOT NULL, \`hair_color\` varchar(255) NOT NULL, \`skin_color\` varchar(255) NOT NULL, \`eye_color\` varchar(255) NOT NULL, \`birth_year\` varchar(255) NOT NULL, \`gender\` varchar(255) NOT NULL, \`homeworldId\` int NULL, UNIQUE INDEX \`IDX_e7ec00b080e693706a6eaa6d31\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`films\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL DEFAULT 'unknown', \`created\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`edited\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`episode_id\` varchar(255) NOT NULL, \`opening_crawl\` longtext NOT NULL, \`director\` varchar(255) NOT NULL, \`producer\` varchar(255) NOT NULL, \`release_date\` date NOT NULL, UNIQUE INDEX \`IDX_936e1cc7dc8c65844638219255\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`username\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`roles\` enum ('user', 'admin') NOT NULL, PRIMARY KEY (\`username\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`planets_images_relations\` (\`planetsId\` int NOT NULL, \`filesId\` int NOT NULL, \`filesName\` varchar(255) NOT NULL, INDEX \`IDX_ef50df7808dee6132360ad7911\` (\`planetsId\`), INDEX \`IDX_2d30704fbfe94fedaac5f88ea4\` (\`filesId\`, \`filesName\`), PRIMARY KEY (\`planetsId\`, \`filesId\`, \`filesName\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`species_images_relaitions\` (\`speciesId\` int NOT NULL, \`filesId\` int NOT NULL, \`filesName\` varchar(255) NOT NULL, INDEX \`IDX_0ae82038e47ccee4c6fbe94ddd\` (\`speciesId\`), INDEX \`IDX_fac3734703d00b96f58f9ff822\` (\`filesId\`, \`filesName\`), PRIMARY KEY (\`speciesId\`, \`filesId\`, \`filesName\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`starships_images_relations\` (\`starshipsId\` int NOT NULL, \`filesId\` int NOT NULL, \`filesName\` varchar(255) NOT NULL, INDEX \`IDX_11d07b971bbbea534a8501db74\` (\`starshipsId\`), INDEX \`IDX_d3bd1761224be32d251998a0d5\` (\`filesId\`, \`filesName\`), PRIMARY KEY (\`starshipsId\`, \`filesId\`, \`filesName\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vehicles_images_relations\` (\`vehiclesId\` int NOT NULL, \`filesId\` int NOT NULL, \`filesName\` varchar(255) NOT NULL, INDEX \`IDX_b3a8dcaea5e7e80f19554a669f\` (\`vehiclesId\`), INDEX \`IDX_bfedf785362ac689f41c2d1bf6\` (\`filesId\`, \`filesName\`), PRIMARY KEY (\`vehiclesId\`, \`filesId\`, \`filesName\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`people_species_relations\` (\`peopleId\` int NOT NULL, \`speciesId\` int NOT NULL, INDEX \`IDX_35b02448905a492d6af12dfec5\` (\`peopleId\`), INDEX \`IDX_c04639938a10add359171f6c1d\` (\`speciesId\`), PRIMARY KEY (\`peopleId\`, \`speciesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`people_vehicles_relations\` (\`peopleId\` int NOT NULL, \`vehiclesId\` int NOT NULL, INDEX \`IDX_d90a6e6141113802b33f69c5ba\` (\`peopleId\`), INDEX \`IDX_f7111296d2bd6560e279a46bb3\` (\`vehiclesId\`), PRIMARY KEY (\`peopleId\`, \`vehiclesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`people_starships_relations\` (\`peopleId\` int NOT NULL, \`starshipsId\` int NOT NULL, INDEX \`IDX_676ef55c820cc40ac6b546ce4f\` (\`peopleId\`), INDEX \`IDX_e317254f438d65992f125408e1\` (\`starshipsId\`), PRIMARY KEY (\`peopleId\`, \`starshipsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`people_images_relations\` (\`peopleId\` int NOT NULL, \`filesId\` int NOT NULL, \`filesName\` varchar(255) NOT NULL, INDEX \`IDX_9c2960c88d502a3c4a83fb5ef3\` (\`peopleId\`), INDEX \`IDX_bea267ae32079b27f5df39e8c4\` (\`filesId\`, \`filesName\`), PRIMARY KEY (\`peopleId\`, \`filesId\`, \`filesName\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`films_people_relations\` (\`filmsId\` int NOT NULL, \`peopleId\` int NOT NULL, INDEX \`IDX_2dde2abdf8fb24c7cf88d311a4\` (\`filmsId\`), INDEX \`IDX_52714c6cd70e38ed51f0bd7694\` (\`peopleId\`), PRIMARY KEY (\`filmsId\`, \`peopleId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`films_planets_relations\` (\`filmsId\` int NOT NULL, \`planetsId\` int NOT NULL, INDEX \`IDX_66eabe5ebc57a468f412eead55\` (\`filmsId\`), INDEX \`IDX_9c27031455638f1d4d5e23cda5\` (\`planetsId\`), PRIMARY KEY (\`filmsId\`, \`planetsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`films_starships_relations\` (\`filmsId\` int NOT NULL, \`starshipsId\` int NOT NULL, INDEX \`IDX_325ef5471d19b917f5a80c45b8\` (\`filmsId\`), INDEX \`IDX_69d442790d2996ad11e65e3346\` (\`starshipsId\`), PRIMARY KEY (\`filmsId\`, \`starshipsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`films_vehicles_relations\` (\`filmsId\` int NOT NULL, \`vehiclesId\` int NOT NULL, INDEX \`IDX_72036db0afe6abfc6caa3537b3\` (\`filmsId\`), INDEX \`IDX_6e6272527a985a1a7d2b3f518d\` (\`vehiclesId\`), PRIMARY KEY (\`filmsId\`, \`vehiclesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`films_species_relations\` (\`filmsId\` int NOT NULL, \`speciesId\` int NOT NULL, INDEX \`IDX_123a405ba0dd146693fd1407d9\` (\`filmsId\`), INDEX \`IDX_3333829b298f3631a9ec6db80e\` (\`speciesId\`), PRIMARY KEY (\`filmsId\`, \`speciesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`films_images_relations\` (\`filmsId\` int NOT NULL, \`filesId\` int NOT NULL, \`filesName\` varchar(255) NOT NULL, INDEX \`IDX_bf924781782018ef2225277ca0\` (\`filmsId\`), INDEX \`IDX_7a6d9c02e854d3a586bbbaeb7e\` (\`filesId\`, \`filesName\`), PRIMARY KEY (\`filmsId\`, \`filesId\`, \`filesName\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`species\` ADD CONSTRAINT \`FK_3427f7c92316561d7131c296bc6\` FOREIGN KEY (\`homeworldId\`) REFERENCES \`planets\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`people\` ADD CONSTRAINT \`FK_8f79bb098a482fa585da15ef3a6\` FOREIGN KEY (\`homeworldId\`) REFERENCES \`planets\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`planets_images_relations\` ADD CONSTRAINT \`FK_ef50df7808dee6132360ad79110\` FOREIGN KEY (\`planetsId\`) REFERENCES \`planets\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`planets_images_relations\` ADD CONSTRAINT \`FK_2d30704fbfe94fedaac5f88ea40\` FOREIGN KEY (\`filesId\`, \`filesName\`) REFERENCES \`files\`(\`id\`,\`name\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`species_images_relaitions\` ADD CONSTRAINT \`FK_0ae82038e47ccee4c6fbe94ddd3\` FOREIGN KEY (\`speciesId\`) REFERENCES \`species\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`species_images_relaitions\` ADD CONSTRAINT \`FK_fac3734703d00b96f58f9ff8222\` FOREIGN KEY (\`filesId\`, \`filesName\`) REFERENCES \`files\`(\`id\`,\`name\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`starships_images_relations\` ADD CONSTRAINT \`FK_11d07b971bbbea534a8501db746\` FOREIGN KEY (\`starshipsId\`) REFERENCES \`starships\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`starships_images_relations\` ADD CONSTRAINT \`FK_d3bd1761224be32d251998a0d5e\` FOREIGN KEY (\`filesId\`, \`filesName\`) REFERENCES \`files\`(\`id\`,\`name\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`vehicles_images_relations\` ADD CONSTRAINT \`FK_b3a8dcaea5e7e80f19554a669fa\` FOREIGN KEY (\`vehiclesId\`) REFERENCES \`vehicles\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`vehicles_images_relations\` ADD CONSTRAINT \`FK_bfedf785362ac689f41c2d1bf6c\` FOREIGN KEY (\`filesId\`, \`filesName\`) REFERENCES \`files\`(\`id\`,\`name\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`people_species_relations\` ADD CONSTRAINT \`FK_35b02448905a492d6af12dfec5a\` FOREIGN KEY (\`peopleId\`) REFERENCES \`people\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`people_species_relations\` ADD CONSTRAINT \`FK_c04639938a10add359171f6c1d6\` FOREIGN KEY (\`speciesId\`) REFERENCES \`species\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`people_vehicles_relations\` ADD CONSTRAINT \`FK_d90a6e6141113802b33f69c5bad\` FOREIGN KEY (\`peopleId\`) REFERENCES \`people\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`people_vehicles_relations\` ADD CONSTRAINT \`FK_f7111296d2bd6560e279a46bb3f\` FOREIGN KEY (\`vehiclesId\`) REFERENCES \`vehicles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`people_starships_relations\` ADD CONSTRAINT \`FK_676ef55c820cc40ac6b546ce4f2\` FOREIGN KEY (\`peopleId\`) REFERENCES \`people\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`people_starships_relations\` ADD CONSTRAINT \`FK_e317254f438d65992f125408e18\` FOREIGN KEY (\`starshipsId\`) REFERENCES \`starships\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`people_images_relations\` ADD CONSTRAINT \`FK_9c2960c88d502a3c4a83fb5ef34\` FOREIGN KEY (\`peopleId\`) REFERENCES \`people\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`people_images_relations\` ADD CONSTRAINT \`FK_bea267ae32079b27f5df39e8c48\` FOREIGN KEY (\`filesId\`, \`filesName\`) REFERENCES \`files\`(\`id\`,\`name\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`films_people_relations\` ADD CONSTRAINT \`FK_2dde2abdf8fb24c7cf88d311a48\` FOREIGN KEY (\`filmsId\`) REFERENCES \`films\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`films_people_relations\` ADD CONSTRAINT \`FK_52714c6cd70e38ed51f0bd7694f\` FOREIGN KEY (\`peopleId\`) REFERENCES \`people\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`films_planets_relations\` ADD CONSTRAINT \`FK_66eabe5ebc57a468f412eead55d\` FOREIGN KEY (\`filmsId\`) REFERENCES \`films\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`films_planets_relations\` ADD CONSTRAINT \`FK_9c27031455638f1d4d5e23cda51\` FOREIGN KEY (\`planetsId\`) REFERENCES \`planets\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`films_starships_relations\` ADD CONSTRAINT \`FK_325ef5471d19b917f5a80c45b85\` FOREIGN KEY (\`filmsId\`) REFERENCES \`films\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`films_starships_relations\` ADD CONSTRAINT \`FK_69d442790d2996ad11e65e33467\` FOREIGN KEY (\`starshipsId\`) REFERENCES \`starships\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`films_vehicles_relations\` ADD CONSTRAINT \`FK_72036db0afe6abfc6caa3537b38\` FOREIGN KEY (\`filmsId\`) REFERENCES \`films\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`films_vehicles_relations\` ADD CONSTRAINT \`FK_6e6272527a985a1a7d2b3f518da\` FOREIGN KEY (\`vehiclesId\`) REFERENCES \`vehicles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`films_species_relations\` ADD CONSTRAINT \`FK_123a405ba0dd146693fd1407d98\` FOREIGN KEY (\`filmsId\`) REFERENCES \`films\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`films_species_relations\` ADD CONSTRAINT \`FK_3333829b298f3631a9ec6db80ef\` FOREIGN KEY (\`speciesId\`) REFERENCES \`species\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`films_images_relations\` ADD CONSTRAINT \`FK_bf924781782018ef2225277ca04\` FOREIGN KEY (\`filmsId\`) REFERENCES \`films\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`films_images_relations\` ADD CONSTRAINT \`FK_7a6d9c02e854d3a586bbbaeb7e0\` FOREIGN KEY (\`filesId\`, \`filesName\`) REFERENCES \`files\`(\`id\`,\`name\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`films_images_relations\` DROP FOREIGN KEY \`FK_7a6d9c02e854d3a586bbbaeb7e0\``);
        await queryRunner.query(`ALTER TABLE \`films_images_relations\` DROP FOREIGN KEY \`FK_bf924781782018ef2225277ca04\``);
        await queryRunner.query(`ALTER TABLE \`films_species_relations\` DROP FOREIGN KEY \`FK_3333829b298f3631a9ec6db80ef\``);
        await queryRunner.query(`ALTER TABLE \`films_species_relations\` DROP FOREIGN KEY \`FK_123a405ba0dd146693fd1407d98\``);
        await queryRunner.query(`ALTER TABLE \`films_vehicles_relations\` DROP FOREIGN KEY \`FK_6e6272527a985a1a7d2b3f518da\``);
        await queryRunner.query(`ALTER TABLE \`films_vehicles_relations\` DROP FOREIGN KEY \`FK_72036db0afe6abfc6caa3537b38\``);
        await queryRunner.query(`ALTER TABLE \`films_starships_relations\` DROP FOREIGN KEY \`FK_69d442790d2996ad11e65e33467\``);
        await queryRunner.query(`ALTER TABLE \`films_starships_relations\` DROP FOREIGN KEY \`FK_325ef5471d19b917f5a80c45b85\``);
        await queryRunner.query(`ALTER TABLE \`films_planets_relations\` DROP FOREIGN KEY \`FK_9c27031455638f1d4d5e23cda51\``);
        await queryRunner.query(`ALTER TABLE \`films_planets_relations\` DROP FOREIGN KEY \`FK_66eabe5ebc57a468f412eead55d\``);
        await queryRunner.query(`ALTER TABLE \`films_people_relations\` DROP FOREIGN KEY \`FK_52714c6cd70e38ed51f0bd7694f\``);
        await queryRunner.query(`ALTER TABLE \`films_people_relations\` DROP FOREIGN KEY \`FK_2dde2abdf8fb24c7cf88d311a48\``);
        await queryRunner.query(`ALTER TABLE \`people_images_relations\` DROP FOREIGN KEY \`FK_bea267ae32079b27f5df39e8c48\``);
        await queryRunner.query(`ALTER TABLE \`people_images_relations\` DROP FOREIGN KEY \`FK_9c2960c88d502a3c4a83fb5ef34\``);
        await queryRunner.query(`ALTER TABLE \`people_starships_relations\` DROP FOREIGN KEY \`FK_e317254f438d65992f125408e18\``);
        await queryRunner.query(`ALTER TABLE \`people_starships_relations\` DROP FOREIGN KEY \`FK_676ef55c820cc40ac6b546ce4f2\``);
        await queryRunner.query(`ALTER TABLE \`people_vehicles_relations\` DROP FOREIGN KEY \`FK_f7111296d2bd6560e279a46bb3f\``);
        await queryRunner.query(`ALTER TABLE \`people_vehicles_relations\` DROP FOREIGN KEY \`FK_d90a6e6141113802b33f69c5bad\``);
        await queryRunner.query(`ALTER TABLE \`people_species_relations\` DROP FOREIGN KEY \`FK_c04639938a10add359171f6c1d6\``);
        await queryRunner.query(`ALTER TABLE \`people_species_relations\` DROP FOREIGN KEY \`FK_35b02448905a492d6af12dfec5a\``);
        await queryRunner.query(`ALTER TABLE \`vehicles_images_relations\` DROP FOREIGN KEY \`FK_bfedf785362ac689f41c2d1bf6c\``);
        await queryRunner.query(`ALTER TABLE \`vehicles_images_relations\` DROP FOREIGN KEY \`FK_b3a8dcaea5e7e80f19554a669fa\``);
        await queryRunner.query(`ALTER TABLE \`starships_images_relations\` DROP FOREIGN KEY \`FK_d3bd1761224be32d251998a0d5e\``);
        await queryRunner.query(`ALTER TABLE \`starships_images_relations\` DROP FOREIGN KEY \`FK_11d07b971bbbea534a8501db746\``);
        await queryRunner.query(`ALTER TABLE \`species_images_relaitions\` DROP FOREIGN KEY \`FK_fac3734703d00b96f58f9ff8222\``);
        await queryRunner.query(`ALTER TABLE \`species_images_relaitions\` DROP FOREIGN KEY \`FK_0ae82038e47ccee4c6fbe94ddd3\``);
        await queryRunner.query(`ALTER TABLE \`planets_images_relations\` DROP FOREIGN KEY \`FK_2d30704fbfe94fedaac5f88ea40\``);
        await queryRunner.query(`ALTER TABLE \`planets_images_relations\` DROP FOREIGN KEY \`FK_ef50df7808dee6132360ad79110\``);
        await queryRunner.query(`ALTER TABLE \`people\` DROP FOREIGN KEY \`FK_8f79bb098a482fa585da15ef3a6\``);
        await queryRunner.query(`ALTER TABLE \`species\` DROP FOREIGN KEY \`FK_3427f7c92316561d7131c296bc6\``);
        await queryRunner.query(`DROP INDEX \`IDX_7a6d9c02e854d3a586bbbaeb7e\` ON \`films_images_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_bf924781782018ef2225277ca0\` ON \`films_images_relations\``);
        await queryRunner.query(`DROP TABLE \`films_images_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_3333829b298f3631a9ec6db80e\` ON \`films_species_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_123a405ba0dd146693fd1407d9\` ON \`films_species_relations\``);
        await queryRunner.query(`DROP TABLE \`films_species_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_6e6272527a985a1a7d2b3f518d\` ON \`films_vehicles_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_72036db0afe6abfc6caa3537b3\` ON \`films_vehicles_relations\``);
        await queryRunner.query(`DROP TABLE \`films_vehicles_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_69d442790d2996ad11e65e3346\` ON \`films_starships_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_325ef5471d19b917f5a80c45b8\` ON \`films_starships_relations\``);
        await queryRunner.query(`DROP TABLE \`films_starships_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_9c27031455638f1d4d5e23cda5\` ON \`films_planets_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_66eabe5ebc57a468f412eead55\` ON \`films_planets_relations\``);
        await queryRunner.query(`DROP TABLE \`films_planets_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_52714c6cd70e38ed51f0bd7694\` ON \`films_people_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_2dde2abdf8fb24c7cf88d311a4\` ON \`films_people_relations\``);
        await queryRunner.query(`DROP TABLE \`films_people_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_bea267ae32079b27f5df39e8c4\` ON \`people_images_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_9c2960c88d502a3c4a83fb5ef3\` ON \`people_images_relations\``);
        await queryRunner.query(`DROP TABLE \`people_images_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_e317254f438d65992f125408e1\` ON \`people_starships_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_676ef55c820cc40ac6b546ce4f\` ON \`people_starships_relations\``);
        await queryRunner.query(`DROP TABLE \`people_starships_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_f7111296d2bd6560e279a46bb3\` ON \`people_vehicles_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_d90a6e6141113802b33f69c5ba\` ON \`people_vehicles_relations\``);
        await queryRunner.query(`DROP TABLE \`people_vehicles_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_c04639938a10add359171f6c1d\` ON \`people_species_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_35b02448905a492d6af12dfec5\` ON \`people_species_relations\``);
        await queryRunner.query(`DROP TABLE \`people_species_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_bfedf785362ac689f41c2d1bf6\` ON \`vehicles_images_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_b3a8dcaea5e7e80f19554a669f\` ON \`vehicles_images_relations\``);
        await queryRunner.query(`DROP TABLE \`vehicles_images_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_d3bd1761224be32d251998a0d5\` ON \`starships_images_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_11d07b971bbbea534a8501db74\` ON \`starships_images_relations\``);
        await queryRunner.query(`DROP TABLE \`starships_images_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_fac3734703d00b96f58f9ff822\` ON \`species_images_relaitions\``);
        await queryRunner.query(`DROP INDEX \`IDX_0ae82038e47ccee4c6fbe94ddd\` ON \`species_images_relaitions\``);
        await queryRunner.query(`DROP TABLE \`species_images_relaitions\``);
        await queryRunner.query(`DROP INDEX \`IDX_2d30704fbfe94fedaac5f88ea4\` ON \`planets_images_relations\``);
        await queryRunner.query(`DROP INDEX \`IDX_ef50df7808dee6132360ad7911\` ON \`planets_images_relations\``);
        await queryRunner.query(`DROP TABLE \`planets_images_relations\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_936e1cc7dc8c65844638219255\` ON \`films\``);
        await queryRunner.query(`DROP TABLE \`films\``);
        await queryRunner.query(`DROP INDEX \`IDX_e7ec00b080e693706a6eaa6d31\` ON \`people\``);
        await queryRunner.query(`DROP TABLE \`people\``);
        await queryRunner.query(`DROP INDEX \`IDX_aa397b791341ed3615397050d4\` ON \`vehicles\``);
        await queryRunner.query(`DROP TABLE \`vehicles\``);
        await queryRunner.query(`DROP INDEX \`IDX_41580e76da7903fb3827a3510e\` ON \`starships\``);
        await queryRunner.query(`DROP TABLE \`starships\``);
        await queryRunner.query(`DROP INDEX \`REL_3427f7c92316561d7131c296bc\` ON \`species\``);
        await queryRunner.query(`DROP INDEX \`IDX_1adf701cac3b2c0f8bacb54774\` ON \`species\``);
        await queryRunner.query(`DROP TABLE \`species\``);
        await queryRunner.query(`DROP INDEX \`IDX_70a170f032a2ca04a6ec6eb2d9\` ON \`planets\``);
        await queryRunner.query(`DROP TABLE \`planets\``);
        await queryRunner.query(`DROP TABLE \`files\``);
    }

}
